const ERRORS = {
	ACCOUNT_EXISTS: 'Account already exists.',
	UNKNOWN_ERROR: 'UNKNOWN_ERROR',
	BAD_REQUEST: 'BAD_REQUEST',
	INTEGRITY_ERROR: 'INTEGRITY_ERROR',
	VALIDATION_ERROR: 'VALIDATION_ERROR',
	BYBIT_JSON_ERROR: 'BYBIT_JSON_ERROR',
	BYBIT_HTML_ERROR: 'BYBIT_HTML_ERROR',
	BYBIT_COMPONENT_ERROR: 'BYBIT_COMPONENT_ERROR',
	INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
};

export default ERRORS;
