const ENDPOINTS = {
	accounts: '/accounts',
	update_account: '/update-account',
	groups: '/filter/groups',
	import_account: '/import-account',
	login_account: '/private/login',
	logout_account: '/private/logout',
	register_account: '/private/register',
	update_profile: '/private/profile',
	finance_accounts: '/private/finance-accounts',
	enable_2fa: '/private/enable-2fa',
	disable_2fa: '/private/disable-2fa',
	finance_accounts_db: '/finance-accounts',
	custom_request: '/public/custom-request',
	license: '/license',
	permission: '/public/permission',
	login_name: '/private/login-name',
	get_captcha: '/private/captcha/get',
	recaptcha_v2_solve: '/private/captcha/recaptcha/v2/solve',
	recaptcha_v2_verify: '/private/captcha/recaptcha/v2/verify',
	geetest_v4_solve: '/private/captcha/geetest/v4/solve',
	geetest_v4_verify: '/private/captcha/geetest/v4/verify',
	verify_risk_token: '/private/risk/verify',
	risk_token: '/private/risk/token',
	get_risk_components: '/private/risk/components',
	send_email_code: '/private/risk/send-email-code',
	imap_scanner: '/imap/scan',
	withdraw_addresses: '/private/withdraw/addresses',
	set_preferences: '/private/set-preferences',
	coins_chains: '/private/withdraw/coins-chains',
	enable_whitelist: '/private/withdraw/enable-whitelist',
	add_withdraw_address: '/private/withdraw/add-address',
	is_email_exist: '/private/is-email-exist',
};

export default ENDPOINTS;
