const FINANCE_ACCOUNT_TYPE = {
	ACCOUNT_TYPE_BOT: 'ACCOUNT_TYPE_BOT',
	ACCOUNT_TYPE_MT4: 'ACCOUNT_TYPE_MT4',
	ACCOUNT_TYPE_MT5: 'ACCOUNT_TYPE_MT5',
	ACCOUNT_TYPE_OPTION: 'ACCOUNT_TYPE_OPTION',
	ACCOUNT_TYPE_SPOT: 'ACCOUNT_TYPE_SPOT',
	ACCOUNT_TYPE_FUND: 'ACCOUNT_TYPE_FUND',
	ACCOUNT_TYPE_UNIFIED: 'ACCOUNT_TYPE_UNIFIED',
	ACCOUNT_TYPE_C2C_YBB: 'ACCOUNT_TYPE_C2C_YBB',
	ACCOUNT_TYPE_CONTRACT: 'ACCOUNT_TYPE_CONTRACT',
	ACCOUNT_TYPE_LAUNCHPOOL: 'ACCOUNT_TYPE_LAUNCHPOOL',
	ACCOUNT_TYPE_COPY_PRO: 'ACCOUNT_TYPE_COPY_PRO',
	ACCOUNT_TYPE_COPY_TRADE: 'ACCOUNT_TYPE_COPY_TRADE',
	ACCOUNT_TYPE_COPY_TRADE_ALL: 'ACCOUNT_TYPE_COPY_TRADE_ALL',
	ACCOUNT_TYPE_INVESTMENT: 'ACCOUNT_TYPE_INVESTMENT',
	ACCOUNT_TYPE_PLEDGE_LOANS: 'ACCOUNT_TYPE_PLEDGE_LOANS',
	ACCOUNT_TYPE_FIXED_RATE_LOAN: 'ACCOUNT_TYPE_FIXED_RATE_LOAN',
	ACCOUNT_TYPE_PRE_MARKET_TRADING: 'ACCOUNT_TYPE_PRE_MARKET_TRADING',
	ACCOUNT_TYPE_MARGIN_STAKE: 'ACCOUNT_TYPE_MARGIN_STAKE',
};

export const FINANCE_ACCOUNT_TYPE_TITLE = {
	[FINANCE_ACCOUNT_TYPE.ACCOUNT_TYPE_FUND]: 'Funding',
	[FINANCE_ACCOUNT_TYPE.ACCOUNT_TYPE_UNIFIED]: 'Unified Trading',
};

export default FINANCE_ACCOUNT_TYPE;
